site_name: ablazed
site_description: session api
repo_url: https://github.com/tomascoelhocruz/testbeapp
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/tomascoelhocruz">tomascoelhocruz</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
